language: ruby
before_install:
  - bundle config build.nokogiri --use-system-libraries
bundler_args: --without development
cache: bundler
rvm: 2.1.2
before_script:
  - psql -c 'create database timecard_test;' -U postgres
  - cp config/database.yml.sample config/database.yml
script:
  - bundle exec rake db:setup
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: 6vEL8b0qwlzdN7An4cmlV9tGHoEJR9gRYPXEnVPzG1DAkwv4OvF0a+uXSp26tjSjNwCcyKtgbkdTEPI5CjmHmwTJ1l60o/COLtRv9zbZBYc/P4mI7N4zbtW0eNWM78VSfCHKeaZs+0thackpVqDw9k4vpAJrxDt3G9w9XJPUons=
  app: timecard-rails
  on:
    repo: timecard/timecard-rails
    branch: master
